services:
    main:
        container_name: neural-noodle
        build: .

        # config for pytorch IPC
        # for gpu access see: https://docs.docker.com/compose/gpu-support/
        stdin_open: true
        tty: true
        ipc: host

        # map ports to host
        ports:
            - "8888:8888"
